First PoC

diff --git a/mkosi.profiles/liveiso/mkosi.extra/usr/sbin/elementary-install b/mkosi.profiles/liveiso/mkosi.extra/usr/sbin/elementary-install
--- a/mkosi.profiles/liveiso/mkosi.extra/usr/sbin/elementary-install
+++ b/mkosi.profiles/liveiso/mkosi.extra/usr/sbin/elementary-install
@@ -3,13 +3,23 @@ set -eo pipefail
 
 echo "Thank you for testing! <3"
 
+apt-get install fzf systemd-repart systemd-boot -y
+
+medium=$(findmnt -rn -t iso9660,udf -o TARGET | head -1)
+extra="$medium/extra"
+raw_src=$(find "$extra" -maxdepth 1 -type f -name '*.raw' | head -n1)
+efi_src=$(find "$extra" -maxdepth 1 -type f -name '*.efi' | head -n1)
+repart_src="$extra/repart.d"
+
+echo "Using source image: $raw_src"
+
 selected_disk=$(lsblk -d -n -p -o NAME,SIZE,MODEL -e 7,11 | fzf \
-  --prompt="Select installation disk (ALL DATA WILL BE LOST): " \
-  --header="NAME          SIZE  MODEL")
+    --prompt="Select installation disk (ALL DATA WILL BE LOST): " \
+    --header="NAME          SIZE  MODEL")
 
 if [ -z "$selected_disk" ]; then
-  echo "Installation aborted: No disk selected."
-  exit 1
+    echo "Installation aborted: No disk selected."
+    exit 1
 fi
 
 dest_dev=$(echo "$selected_disk" | awk '{print $1}')
@@ -22,55 +32,13 @@ sleep 1
 echo "Destroying drive in 1s ..."
 sleep 1
 
+/usr/sbin/wipefs -a "$dest_dev"
+
 systemd-repart \
-  --definitions=/etc/repart-installer/ \
-  --dry-run=no \
-  --empty=force \
-  "$dest_dev"
+    --copy-from="$raw_src" \
+    --definitions="$repart_src" \
+    --dry-run=no \
+    --empty=force \
+    "$dest_dev"
 
-echo "Installing bootloader ..."
-
-sleep 1
-
-udevadm settle
-
-sleep 1
-
-mkdir -p /mnt/esp
-
-target_esp=$(lsblk -n -o PATH,PARTLABEL "$dest_dev" | awk '$2=="esp" {print $1}')
-
-mount -o umask=0077 "$target_esp" /mnt/esp
-
-bootctl install --esp-path=/mnt/esp --no-variables
-
-cp /usr/lib/elementary-install/*.efi /mnt/esp/EFI/Linux/
-
-cat > /mnt/esp/loader/loader.conf <<'EOF'
-timeout 6
-EOF
-
-umount /mnt/esp
-
-
-target_root=$(lsblk -n -o PATH,PARTLABEL "$dest_dev" | awk '$2=="Elementary-root" {print $1}')
-
-if [ -n "$target_root" ]; then
-  mkdir -p /mnt/root
-  mount "$target_root" /mnt/root
-
-  rm -f /mnt/root/etc/lightdm/lightdm.conf.d/12-liveiso.conf
-  rm -f /mnt/root/etc/sudoers.d/liveiso
-
-  if chroot /mnt/root id liveiso &>/dev/null; then
-    chroot /mnt/root userdel -f liveiso
-  fi
-
-  umount /mnt/root
-else
-  echo "Fatal Error, could not cleanup"
-  exit 1
-fi
-
-
-echo "Install done, reboot now"
+echo "Everything is done! Enjoy your stay."
